# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('fee', models.FloatField()),
                ('camera_choices', models.CharField(choices=[('CANON', 'Canon'), ('NIKON', 'Nikon'), ('OLYMPUS', 'Olyumpus')], default='CANON', max_length=2)),
                ('services_choices', models.CharField(choices=[('PORTRAIT', 'Portrait'), ('WEDDING', 'Wedding'), ('AWKWARD', 'Awkward')], default='PORTRAIT', max_length=2)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=100)),
                ('photo_styles', models.CharField(choices=[('BW', 'Black and White'), ('Color', 'Color')], default='BW', max_length=2)),
                ('active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
