# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 01:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='imagerprofile',
            name='active',
        ),
    ]
