# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='camera_choices',
            field=models.CharField(choices=[('CANON', 'Canon'), ('NIKON', 'Nikon'), ('OLYMPUS', 'Olympus'), ('FUJI', 'Fuji')], default='CANON', max_length=50),
        ),
    ]
