# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20171121_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
