language: python
python:
  - '3.6'

services:
  - postgresql

before_script:
  - psql -c "create database imager_test;" -U postgres

install:
  - pip install -r requirements.pip

script:
  - coverage run imagersite/manage.py test imagersite

after_success:
  - coveralls

branches:
  only:
    - master